branch-defaults:
  default:
    environment: udagram-app-api-dev
    group_suffix: null
  main:
    environment: udagram-app-api-dev
deploy:
  artifact: www/Archive.zip
  main:
    environment: null
global:
  application_name: udagram-app-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
